# Generated by Django 2.2.10 on 2020-06-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200609_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedarticles',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Главный тег'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.ManyToManyField(through='articles.PublishedArticles', to='articles.Article', verbose_name='Теги'),
        ),
    ]
